application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      adobe_microservice:
        license: Apache-2.0
        actions:
          generic:
            function: actions/generic/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          publish-events:
            function: actions/publish-events/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              apiKey: $SERVICE_API_KEY
            annotations:
              require-adobe-auth: true
              final: true
          simple-api:
            function: actions/simple-api/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          cron-job:
            function: actions/cron-job/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          upload-to-aem:
            function: actions/upload-to-aem/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: info
              aemHost: https://author-p25321-e288205.adobeaemcloud.com
              aemTargetPath: /content/dam/mcds
              aemUsername: admin
              aemPassword: admin
              aemBearerToken: $AEM_ACCESS_TOKEN
              sourceFolder: ./assets/images
            annotations:
              require-adobe-auth: false
              final: true
            limits:
              timeout: 300000
